listen_addresses = '127.0.0.1'
port = 5432
max_connections = 30
shared_buffers = 128MB
effective_cache_size = 512MB
maintenance_work_mem = 64MB
work_mem = 4MB
wal_buffers = 4MB
min_wal_size = 80MB
max_wal_size = 512MB
checkpoint_completion_target = 0.9
logging_collector = on
log_rotation_age = 1d
log_truncate_on_rotation = on
log_filename = 'postgresql-%a.log'
