"""Initial single-stand POS schema and immutable financial ledgers."""
from alembic import op
import sqlalchemy as sa
from app.core.integrity import install_integrity_guards

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modifier_groups',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('minimum', sa.Integer(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('CASHIER','SERVER','MANAGER','OWNER_ADMIN')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    op.create_table('business_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_by', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by', sa.String(length=36), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_float_ngwee', sa.Integer(), nullable=False),
    sa.Column('actual_cash_ngwee', sa.Integer(), nullable=True),
    sa.Column('close_snapshot', sa.JSON(), nullable=True),
    sa.Column('next_order_number', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('OPEN','CLOSED')"),
    sa.CheckConstraint('opening_float_ngwee >= 0'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('one_open_business_day', 'business_days', ['status'], unique=True, sqlite_where=sa.text("status = 'OPEN'"), postgresql_where=sa.text("status = 'OPEN'"))
    op.create_table('modifiers',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('group_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_ngwee', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price_ngwee >= 0'),
    sa.ForeignKeyConstraint(['group_id'], ['modifier_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('category_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_counts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=60), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('variance', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('counted_quantity >= 0'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity != 0'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference'), 'stock_movements', ['reference'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_day_id', sa.String(length=36), nullable=False),
    sa.Column('amount_ngwee', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_ngwee != 0'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_movements_business_day_id'), 'cash_movements', ['business_day_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('business_day_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_ngwee', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('NEW','PREPARING','READY','SERVED')"),
    sa.CheckConstraint('total_ngwee >= 0'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_day_id', 'number'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_orders_business_day_id'), 'orders', ['business_day_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('product_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_ngwee', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price_ngwee >= 0'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_ngwee', sa.Integer(), nullable=False),
    sa.Column('total_ngwee', sa.Integer(), nullable=False),
    sa.Column('modifier_names', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.CheckConstraint('total_ngwee = quantity * unit_price_ngwee'),
    sa.CheckConstraint('unit_price_ngwee >= 0'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount_ngwee', sa.Integer(), nullable=False),
    sa.Column('tendered_ngwee', sa.Integer(), nullable=True),
    sa.Column('change_ngwee', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('CASH','MOBILE_MONEY_MANUAL','CARD_MANUAL')"),
    sa.CheckConstraint("status IN ('PENDING','CONFIRMED','FAILED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED')"),
    sa.CheckConstraint('amount_ngwee >= 0'),
    sa.CheckConstraint('change_ngwee >= 0'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('method', 'provider', 'reference', name='unique_external_payment_reference'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('recipe_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('variant_id', sa.String(length=60), nullable=True),
    sa.Column('modifier_id', sa.String(length=60), nullable=True),
    sa.Column('item_id', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.CheckConstraint('(variant_id IS NULL) != (modifier_id IS NULL)'),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifiers.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('business_day_id', sa.String(length=36), nullable=False),
    sa.Column('amount_ngwee', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount_ngwee >= 0'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['business_day_id'], ['business_days.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_refunds_business_day_id'), 'refunds', ['business_day_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(sa.text('INSERT INTO branch_lock (id, revision) VALUES (1, 0)'))
    install_integrity_guards(op.get_bind())


def downgrade():
    raise RuntimeError('Destructive downgrade is disabled for permanent financial history. Restore a verified backup instead.')
